#!/usr/bin/env python3
"""Generate the committed MP4/M4A + ALAC capability corpus."""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import struct
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "tests" / "fixtures" / "native-alac-v1"
FFMPEG_VERSION = "8.0.1"
PCM_GUID = bytes.fromhex("0100000000001000800000aa00389b71")
README = """# native-alac-v1

This corpus fixes the stable, in-process MP4/M4A + ALAC route. Every ALAC
fixture has a deterministic WAV twin containing identical integer PCM. The
manifest records byte hashes, geometry, encoder identity, twin relationships,
and normalized interleaved `f64` fingerprints.

Normal tests consume the committed bytes and do not require FFmpeg. Exact
regeneration is deliberately pinned to FFmpeg 8.0.1:

```bash
python3 scripts/generate-native-alac-v1.py --check
```

The samples are synthetic, generated by this MIT-licensed repository, and do
not contain personal or copyrighted recordings.
"""


@dataclass(frozen=True)
class Case:
    stem: str
    extension: str
    bits: int
    sample_rate: int
    channels: int
    channel_mask: int
    channel_layout: str
    frames: int
    faststart: bool = False
    title: str | None = None


CASES = (
    Case("alac16-mono-44100", "m4a", 16, 44_100, 1, 0x0004, "mono", 257),
    Case(
        "alac16-stereo-48000-multipacket",
        "m4a",
        16,
        48_000,
        2,
        0x0003,
        "stereo",
        9_001,
        title="MacinMeter deterministic ALAC fixture",
    ),
    Case(
        "alac24-stereo-96000-faststart",
        "mp4",
        24,
        96_000,
        2,
        0x0003,
        "stereo",
        5_003,
        faststart=True,
    ),
    Case("alac24-3ch-48000", "m4a", 24, 48_000, 3, 0x0007, "3.0", 521),
    Case("alac24-4ch-48000", "mp4", 24, 48_000, 4, 0x0107, "4.0", 523),
    Case("alac24-5ch-48000", "m4a", 24, 48_000, 5, 0x0607, "5.0", 527),
    Case("alac24-6ch-48000", "mp4", 24, 48_000, 6, 0x060F, "5.1", 529),
    Case("alac24-7ch-48000", "m4a", 24, 48_000, 7, 0x070F, "6.1(back)", 541),
    Case("alac24-8ch-48000", "mp4", 24, 48_000, 8, 0x06CF, "7.1(wide)", 547),
)


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def script_sha256() -> str:
    return sha256(Path(__file__).read_bytes())


def ffmpeg_identity(executable: str) -> dict[str, str]:
    completed = subprocess.run(
        [executable, "-version"],
        check=True,
        capture_output=True,
        text=True,
    )
    lines = completed.stdout.splitlines()
    if not lines or not lines[0].startswith(f"ffmpeg version {FFMPEG_VERSION}"):
        observed = lines[0] if lines else "<no output>"
        raise SystemExit(
            f"native-alac-v1 requires ffmpeg {FFMPEG_VERSION}; observed: {observed}"
        )
    configuration = next(
        (line for line in lines if line.startswith("configuration:")), ""
    )
    return {
        "tool": "ffmpeg",
        "version": FFMPEG_VERSION,
        "versionLine": lines[0],
        "configurationSha256": sha256(configuration.encode("utf-8")),
    }


def pcm_values(case: Case) -> list[int]:
    peak = (1 << (case.bits - 1)) - 1
    span = peak * 2 + 1
    values: list[int] = []
    for frame in range(case.frames):
        for channel in range(case.channels):
            raw = (
                frame * (7_919 + channel * 131)
                + channel * 104_729
                + (frame // 17) * 65_537
            ) % span
            value = raw - peak
            if frame == channel:
                value = peak
            elif frame == channel + case.channels:
                value = -peak
            elif frame % 257 == 0:
                value = 0
            values.append(value)
    return values


def pack_pcm(values: list[int], bits: int) -> bytes:
    if bits == 16:
        return b"".join(struct.pack("<h", value) for value in values)
    if bits == 24:
        return b"".join((value & 0xFF_FFFF).to_bytes(3, "little") for value in values)
    raise AssertionError(bits)


def riff_chunk(kind: bytes, payload: bytes) -> bytes:
    padding = b"\0" if len(payload) % 2 else b""
    return kind + struct.pack("<I", len(payload)) + payload + padding


def wave_bytes(case: Case, values: list[int]) -> bytes:
    bytes_per_sample = case.bits // 8
    block_align = case.channels * bytes_per_sample
    byte_rate = case.sample_rate * block_align
    if case.channels <= 2:
        fmt = struct.pack(
            "<HHIIHH",
            1,
            case.channels,
            case.sample_rate,
            byte_rate,
            block_align,
            case.bits,
        )
    else:
        fmt = struct.pack(
            "<HHIIHHHHI",
            0xFFFE,
            case.channels,
            case.sample_rate,
            byte_rate,
            block_align,
            case.bits,
            22,
            case.bits,
            case.channel_mask,
        ) + PCM_GUID
    body = b"WAVE" + riff_chunk(b"fmt ", fmt) + riff_chunk(
        b"data", pack_pcm(values, case.bits)
    )
    return b"RIFF" + struct.pack("<I", len(body)) + body


def normalized_pcm_sha256(values: list[int], bits: int) -> str:
    divisor = float(1 << (bits - 1))
    digest = hashlib.sha256()
    for value in values:
        digest.update(struct.pack("<d", value / divisor))
    return digest.hexdigest()


def encode_alac(
    executable: str,
    case: Case,
    wave_path: Path,
    output_path: Path,
) -> list[str]:
    command = [
        executable,
        "-y",
        "-hide_banner",
        "-loglevel",
        "error",
        "-fflags",
        "+bitexact",
        "-i",
        str(wave_path),
        "-map_metadata",
        "-1",
        "-vn",
        "-c:a",
        "alac",
        "-compression_level",
        "2",
        "-flags:a",
        "+bitexact",
        "-channel_layout:a",
        case.channel_layout,
    ]
    if case.faststart:
        command.extend(["-movflags", "+faststart"])
    if case.title is not None:
        command.extend(["-metadata", f"title={case.title}"])
    command.extend(["-f", "ipod" if case.extension == "m4a" else "mp4", str(output_path)])
    subprocess.run(command, check=True)
    recorded = ["ffmpeg", *command[1:-1], f"<output>.{case.extension}"]
    return normalize_recorded_paths(recorded, output_path.parent)


def run_negative_command(
    executable: str, arguments: list[str], output_path: Path
) -> list[str]:
    command = [
        executable,
        "-y",
        "-hide_banner",
        "-loglevel",
        "error",
        *arguments,
        str(output_path),
    ]
    subprocess.run(command, check=True)
    recorded = ["ffmpeg", *command[1:-1], f"<output>{output_path.suffix}"]
    return normalize_recorded_paths(recorded, output_path.parent)


def normalize_recorded_paths(command: list[str], corpus: Path) -> list[str]:
    prefix = f"{corpus}/"
    return [
        f"<corpus>/{Path(argument).name}"
        if argument.startswith(prefix)
        else argument
        for argument in command
    ]


def find_box_type(data: bytes, kind: bytes) -> int:
    position = data.find(kind)
    while position >= 4:
        size = struct.unpack(">I", data[position - 4 : position])[0]
        if size == 1:
            if position + 12 <= len(data):
                extended = struct.unpack(">Q", data[position + 4 : position + 12])[0]
                if extended >= 16 and position - 4 + extended <= len(data):
                    return position
        elif size >= 8 and position - 4 + size <= len(data):
            return position
        position = data.find(kind, position + 1)
    raise ValueError(f"missing valid {kind!r} box")


def inspect_generated_alac(data: bytes) -> dict[str, object]:
    top_level_boxes: list[dict[str, object]] = []
    position = 0
    while position < len(data):
        if position + 8 > len(data):
            raise ValueError("truncated top-level box")
        size32 = struct.unpack(">I", data[position : position + 4])[0]
        kind = data[position + 4 : position + 8].decode("ascii")
        if size32 == 1:
            if position + 16 > len(data):
                raise ValueError("truncated extended top-level box")
            size = struct.unpack(">Q", data[position + 8 : position + 16])[0]
            size_encoding = 64
        else:
            size = size32
            size_encoding = 32
        if size < (16 if size_encoding == 64 else 8) or position + size > len(data):
            raise ValueError(f"invalid top-level {kind} box size")
        top_level_boxes.append(
            {
                "type": kind,
                "offset": position,
                "sizeBytes": size,
                "sizeEncodingBits": size_encoding,
            }
        )
        position += size

    alac_types: list[int] = []
    search = 0
    while True:
        found = data.find(b"alac", search)
        if found < 0:
            break
        if found >= 4:
            size = struct.unpack(">I", data[found - 4 : found])[0]
            if size >= 8 and found - 4 + size <= len(data):
                alac_types.append(found)
        search = found + 1
    if len(alac_types) != 2:
        raise ValueError(f"expected two ALAC box identifiers, found {len(alac_types)}")
    sample_entry_type, config_type = alac_types
    config_size = struct.unpack(">I", data[config_type - 4 : config_type])[0]
    if data[config_type + 4 : config_type + 8] != b"\0\0\0\0":
        raise ValueError("generated ALAC config full-box field is nonzero")
    cookie = data[config_type + 8 : config_type - 4 + config_size]
    if len(cookie) not in (24, 48):
        raise ValueError(f"unexpected ALAC cookie length {len(cookie)}")

    mdhd = find_box_type(data, b"mdhd")
    mdhd_version = data[mdhd + 4]
    if mdhd_version == 0:
        mdhd_timescale = struct.unpack(">I", data[mdhd + 16 : mdhd + 20])[0]
        mdhd_duration = struct.unpack(">I", data[mdhd + 20 : mdhd + 24])[0]
    elif mdhd_version == 1:
        mdhd_timescale = struct.unpack(">I", data[mdhd + 24 : mdhd + 28])[0]
        mdhd_duration = struct.unpack(">Q", data[mdhd + 28 : mdhd + 36])[0]
    else:
        raise ValueError(f"unexpected mdhd version {mdhd_version}")

    stts = find_box_type(data, b"stts")
    stts_entry_count = struct.unpack(">I", data[stts + 8 : stts + 12])[0]
    stts_packets = 0
    stts_frames = 0
    for entry in range(stts_entry_count):
        offset = stts + 12 + entry * 8
        packet_count, packet_frames = struct.unpack(">II", data[offset : offset + 8])
        stts_packets += packet_count
        stts_frames += packet_count * packet_frames

    stsz = find_box_type(data, b"stsz")
    stsz_default_size = struct.unpack(">I", data[stsz + 8 : stsz + 12])[0]
    stsz_sample_count = struct.unpack(">I", data[stsz + 12 : stsz + 16])[0]

    layout: dict[str, object] = {"mode": "implicit_standard_by_channel_count"}
    if len(cookie) == 48:
        layout = {
            "mode": "explicit_standard_tag",
            "tag": f"0x{struct.unpack('>I', cookie[36:40])[0]:08x}",
        }
    return {
        "topLevelBoxes": top_level_boxes,
        "sampleEntry": {
            "type": "alac",
            "channels": struct.unpack(">H", data[sample_entry_type + 20 : sample_entry_type + 22])[0],
            "sampleRateFixed16_16": f"0x{struct.unpack('>I', data[sample_entry_type + 28 : sample_entry_type + 32])[0]:08x}",
        },
        "cookie": {
            "lengthBytes": len(cookie),
            "frameLength": struct.unpack(">I", cookie[0:4])[0],
            "compatibleVersion": cookie[4],
            "bitDepth": cookie[5],
            "channels": cookie[9],
            "sampleRate": struct.unpack(">I", cookie[20:24])[0],
            "channelLayout": layout,
        },
        "mediaHeader": {
            "version": mdhd_version,
            "timescale": mdhd_timescale,
            "durationFrames": mdhd_duration,
        },
        "sampleTables": {
            "sttsEntryCount": stts_entry_count,
            "sttsPacketCount": stts_packets,
            "sttsFrameCount": stts_frames,
            "stszDefaultSampleSize": stsz_default_size,
            "stszSampleCount": stsz_sample_count,
        },
    }


def build_route_negative_sources(
    destination: Path, executable: str
) -> list[dict[str, object]]:
    stereo = destination / "alac16-stereo-48000-multipacket-twin.wav"
    mono = destination / "alac16-mono-44100-twin.wav"
    specifications = [
        (
            "unsupported-aac.m4a",
            "single AAC audio track",
            [
                "-fflags",
                "+bitexact",
                "-i",
                str(stereo),
                "-map_metadata",
                "-1",
                "-vn",
                "-c:a",
                "aac",
                "-b:a",
                "128k",
                "-flags:a",
                "+bitexact",
                "-f",
                "ipod",
            ],
        ),
        (
            "unsupported-fragmented-alac.mp4",
            "fragmented ALAC ISO BMFF",
            [
                "-fflags",
                "+bitexact",
                "-i",
                str(stereo),
                "-map_metadata",
                "-1",
                "-vn",
                "-c:a",
                "alac",
                "-flags:a",
                "+bitexact",
                "-movflags",
                "frag_keyframe+empty_moov+default_base_moof",
                "-f",
                "mp4",
            ],
        ),
        (
            "unsupported-multitrack-alac.mp4",
            "two ALAC audio tracks",
            [
                "-fflags",
                "+bitexact",
                "-i",
                str(stereo),
                "-i",
                str(mono),
                "-map_metadata",
                "-1",
                "-map",
                "0:a:0",
                "-map",
                "1:a:0",
                "-c:a",
                "alac",
                "-flags:a",
                "+bitexact",
                "-f",
                "mp4",
            ],
        ),
        (
            "unsupported-video-alac.mp4",
            "video track plus one ALAC audio track",
            [
                "-fflags",
                "+bitexact",
                "-f",
                "lavfi",
                "-i",
                "color=c=black:s=16x16:r=25:d=0.2",
                "-i",
                str(stereo),
                "-map_metadata",
                "-1",
                "-map",
                "0:v:0",
                "-map",
                "1:a:0",
                "-c:v",
                "mpeg4",
                "-q:v",
                "31",
                "-flags:v",
                "+bitexact",
                "-c:a",
                "alac",
                "-flags:a",
                "+bitexact",
                "-shortest",
                "-threads",
                "1",
                "-f",
                "mp4",
            ],
        ),
    ]
    sources: list[dict[str, object]] = []
    for name, shape, arguments in specifications:
        output_path = destination / name
        command = run_negative_command(executable, arguments, output_path)
        payload = output_path.read_bytes()
        sources.append(
            {
                "path": name,
                "sha256": sha256(payload),
                "shape": shape,
                "expected": {"code": "unsupported_format", "stage": "probe"},
                "encoderCommand": command,
            }
        )
    return sources


def build_corpus(destination: Path, executable: str) -> dict[str, object]:
    destination.mkdir(parents=True, exist_ok=True)
    (destination / "README.md").write_text(README, encoding="utf-8")
    encoder = ffmpeg_identity(executable)
    fixtures: list[dict[str, object]] = []
    for case in CASES:
        values = pcm_values(case)
        wave_name = f"{case.stem}-twin.wav"
        alac_name = f"{case.stem}.{case.extension}"
        wave_path = destination / wave_name
        alac_path = destination / alac_name
        wave_path.write_bytes(wave_bytes(case, values))
        command = encode_alac(executable, case, wave_path, alac_path)
        alac_bytes = alac_path.read_bytes()
        structure = inspect_generated_alac(alac_bytes)
        cookie = structure["cookie"]
        media_header = structure["mediaHeader"]
        sample_tables = structure["sampleTables"]
        if cookie != {
            "lengthBytes": 24,
            "frameLength": 4096,
            "compatibleVersion": 0,
            "bitDepth": case.bits,
            "channels": case.channels,
            "sampleRate": case.sample_rate,
            "channelLayout": {"mode": "implicit_standard_by_channel_count"},
        }:
            raise ValueError(f"{alac_name}: unexpected ALAC cookie {cookie}")
        if (
            media_header["timescale"] != case.sample_rate
            or media_header["durationFrames"] != case.frames
        ):
            raise ValueError(f"{alac_name}: mdhd geometry disagrees with generated PCM")
        if (
            sample_tables["sttsFrameCount"] != case.frames
            or sample_tables["sttsPacketCount"]
            != sample_tables["stszSampleCount"]
        ):
            raise ValueError(f"{alac_name}: generated ALAC sample tables disagree")
        pcm_hash = normalized_pcm_sha256(values, case.bits)
        common = {
            "sampleRate": case.sample_rate,
            "channels": case.channels,
            "bitsPerSample": case.bits,
            "frames": case.frames,
            "channelMask": f"0x{case.channel_mask:08x}",
            "channelLayout": case.channel_layout,
            "normalizedInterleavedF64LeSha256": pcm_hash,
        }
        fixtures.append(
            {
                "path": wave_name,
                "sha256": sha256(wave_path.read_bytes()),
                "kind": "wave_twin",
                "twin": alac_name,
                **common,
            }
        )
        fixtures.append(
            {
                "path": alac_name,
                "sha256": sha256(alac_bytes),
                "kind": "alac",
                "container": "mp4",
                "codec": "alac",
                "compatibleVersion": 0,
                "frameLength": 4096,
                "faststart": case.faststart,
                "twin": wave_name,
                "encoderCommand": command,
                "isoBmff": structure,
                **common,
            }
        )
    route_negative_sources = build_route_negative_sources(destination, executable)
    manifest: dict[str, object] = {
        "schemaVersion": 1,
        "corpus": "native-alac-v1",
        "generator": {
            "path": "scripts/generate-native-alac-v1.py",
            "sha256": script_sha256(),
            "commands": [
                "python3 scripts/generate-native-alac-v1.py",
                "python3 scripts/generate-native-alac-v1.py --check",
            ],
            "externalToolsRequiredForRegeneration": True,
            "normalTestsRequireExternalTools": False,
        },
        "encoder": encoder,
        "provenance": {
            "kind": "deterministically_generated",
            "copyrightedAudio": False,
            "license": "MIT",
        },
        "fixtures": fixtures,
        "routeNegativeSources": route_negative_sources,
    }
    (destination / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return manifest


def compare_directories(expected: Path, actual: Path) -> None:
    expected_files = sorted(
        path.relative_to(expected) for path in expected.rglob("*") if path.is_file()
    )
    actual_files = sorted(
        path.relative_to(actual) for path in actual.rglob("*") if path.is_file()
    )
    if expected_files != actual_files:
        raise SystemExit(
            "committed native ALAC fixture paths differ from the pinned generator"
        )
    changed = [
        str(path)
        for path in expected_files
        if (expected / path).read_bytes() != (actual / path).read_bytes()
    ]
    if changed:
        raise SystemExit(
            "committed native ALAC fixtures differ from the pinned generator: "
            + ", ".join(changed)
        )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--ffmpeg", default=shutil.which("ffmpeg"))
    args = parser.parse_args()
    if not args.ffmpeg:
        parser.error("ffmpeg is required to regenerate native-alac-v1")

    if args.check:
        if not OUTPUT.is_dir():
            raise SystemExit(f"committed corpus is missing: {OUTPUT}")
        with tempfile.TemporaryDirectory(prefix="macinmeter-native-alac-") as directory:
            generated = Path(directory)
            build_corpus(generated, args.ffmpeg)
            compare_directories(OUTPUT, generated)
        print("native-alac-v1 matches the pinned generator")
        return 0

    with tempfile.TemporaryDirectory(prefix="macinmeter-native-alac-") as directory:
        generated = Path(directory)
        build_corpus(generated, args.ffmpeg)
        OUTPUT.mkdir(parents=True, exist_ok=True)
        for existing in OUTPUT.iterdir():
            if existing.is_file():
                existing.unlink()
        for source in generated.iterdir():
            shutil.copy2(source, OUTPUT / source.name)
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
